version: "2" 

# plugins:
#   eslint:
#     enabled: true
#     channel: "eslint-8"
#     checks:
#       complexity:
#         enabled: true
#     config:
#       config: .eslintrc.js
#       extensions:
#       - .ts
#       - .tsx
#       - .es6
#       - .js
#       - .jsx
#       - .mjs

exclude_paths:
- .github/
- .husky/
- "**/*.js"
- "**/*.d.ts"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 45
  identical-code:
    enabled: true
    config:
      threshold: 45
